### ISSUE TITLE
Cannot get v2.0.0

### ISSUE THREAD

**Issue by piegamesde** [tobiasdiez/EasyBind#20]
I cannot get version 2.0.0 working in Gradle. Maven Central [only knows v1.2.2](https://search.maven.org/artifact/com.tobiasdiez/easybind), and JitPack [fails building](https://jitpack.io/com/github/tobiasdiez/EasyBind/2.0.0/build.log)

**Comment by tobiasdiez** [comment]
Thanks for the heads-up! I indeed forgot to hit the "Publish release" button. Tomorrow, I'll trigger a new release. Until then you can use the snapshot release: https://github.com/tobiasdiez/EasyBind#snapshot-releases

**Comment by tobiasdiez** [comment]
2.1.0 should be on maven now, although it might take a while until it's indexed in the search
https://repo1.maven.org/maven2/com/tobiasdiez/easybind/2.1.0/
