### ISSUE TITLE
Make javafx.base dependency transitive

### ISSUE THREAD

**Issue by apus6** [tobiasdiez/EasyBind#30]
Would it be possible to modify the `requires javafx.base;` into `requires transitive javafx.base;` in `module-info.java`?

This would avoid excluding the dependency in maven or gradle when facing this type of error: 
Package 'com.example' reads package 'javafx.beans' from both 'javafx.base' and 'javafx.base'

**Comment by overheadhunter** [comment]
The issue is explained in detail [in this SO post](https://stackoverflow.com/a/53562029/4014509)

**Comment by tobiasdiez** [comment]
Thanks to @overheadhunter this is now fixed. I also removed the os-specific "classifier" in the pom file. This is contained in Release 2.2, which should be available very soon on maven (I just published it).
