### ISSUE TITLE
Version 2.2.0 doesn't exist in Maven Central 🤔

### ISSUE THREAD

**Issue by guizmaii** [tobiasdiez/EasyBind#40]
Hi,

Just noticed that there's a difference between the last version number here and in the README compared to the last version we can find in Maven.

Here the latest version is tagged `2.2.0` but in Maven Central, the version is `2.2`, is it normal?

See https://mvnrepository.com/artifact/com.tobiasdiez/easybind

**Comment by tobiasdiez** [comment]
Yes, I screwed the version number up :(
https://github.com/tobiasdiez/EasyBind/issues/39

**Comment by guizmaii** [comment]
Thanks for your work on this lib!!! Very useful ❤️
